apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: sijh8rnbr-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/sijh8rnbr-java-quarkus-gitops